name: Remove Studio File from PR

on:
  pull_request:
    branches:
      - main

jobs:
  remove-studio-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Remove Studio YAML
        run: |
          git rm --cached .github/workflows/studio.yml || true
          git commit -m "Auto-remove studio.yml before merging to main" || true
          git push || true
